# Generated by Django 3.2.19 on 2024-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntries', '0004_journalentrylines_reconsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentries',
            name='U_InterTransaction',
            field=models.CharField(blank=True, default='N', max_length=200),
        ),
    ]
