# Generated by Django 3.2.13 on 2023-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20230125_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressextension',
            name='BillToDistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToDistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
