# Generated by Django 3.2.13 on 2023-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PayTermsGrpCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
