# Generated by Django 3.2.13 on 2023-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20230214_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ApprovalStatus',
            field=models.CharField(blank=True, default='Approved', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='ApproverId',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
