# Generated by Django 3.2.13 on 2023-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20230214_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='TaxRate',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
