# Generated by Django 3.2.13 on 2023-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_order_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='UnitPriceown',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
    ]
