# Generated by Django 3.2.13 on 2023-03-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_order_unitpriceown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='UnitPriceown',
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UnitPriceown',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
    ]
