# Generated by Django 3.2.19 on 2023-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_alter_documentlines_unitpriceown'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='LineTotal',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='OpenAmount',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='RemainingOpenQuantity',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
