# Generated by Django 3.2.19 on 2023-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_documentlines_linestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='DocNum',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
