# Generated by Django 3.2.19 on 2023-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_order_docnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ContactPersonCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='CreatedBy',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='DiscountPercent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='DocEntry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='DocNum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='FreeDelivery',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
