# Generated by Django 3.2.19 on 2023-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_auto_20231106_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='Price',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='PriceAfterVAT',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
